import type { DslAst } from '@/features/editor/types/DslAst';
import type { SchemaGenerator } from './SchemaGenerator';
import { TypeMapper } from './TypeMapper';

export class MongoGenerator implements SchemaGenerator {
  generate(ast: DslAst): string {
    let output = `// Mongoose schema generated by SchemaFlow\n`;
    output += `import mongoose from 'mongoose';\n\n`;
    output += `const { Schema } = mongoose;\n\n`;

    for (const table of ast.tables) {
      output += `export const ${table.name}Schema = new Schema({\n`;
      
      for (const col of table.columns) {
        // Skip default generic primary keys as mongo uses _id automatically
        // Unless it's explicitly modeled
        if (col.name === 'id' && col.primaryKey) {
          // Generally Mongoose handles _id, so we can ignore generic id fields
          // or we can map them. We will map them for explicit completeness if they aren't 'id'
          continue;
        }

        const type = TypeMapper.map(col.dataType, 'mongo');
        
        // Find if this column is a foreign key
        const fKeyRef = ast.refs.find(r => r.fromTable === table.name && r.fromColumn === col.name);
        
        output += `  ${col.name}: {\n`;
        
        if (fKeyRef) {
          output += `    type: Schema.Types.ObjectId,\n`;
          output += `    ref: '${fKeyRef.toTable}',\n`;
        } else {
          output += `    type: ${type},\n`;
        }
        
        if (col.notNull && !col.primaryKey) {
          output += `    required: true,\n`;
        }
        if (col.unique) {
          output += `    unique: true,\n`;
        }
        if (col.defaultValue) {
          if (col.defaultValue.toLowerCase() === 'now()') {
            output += `    default: Date.now,\n`;
          } else if (type === 'String') {
            output += `    default: '${col.defaultValue}',\n`;
          } else {
            output += `    default: ${col.defaultValue},\n`;
          }
        }
        
        output += `  },\n`;
      }
      
      output += `});\n\n`;
      output += `export const ${table.name} = mongoose.model('${table.name}', ${table.name}Schema);\n\n`;
    }

    return output;
  }
}
