import type { DslAst } from '@/features/editor/types/DslAst';
import type { SchemaGenerator } from './SchemaGenerator';
import { TypeMapper } from './TypeMapper';

export class PostgresGenerator implements SchemaGenerator {
  generate(ast: DslAst): string {
    let output = `-- PostgreSQL schema generated by SchemaFlow\n\n`;

    // 1. Generate Tables
    for (const table of ast.tables) {
      output += `CREATE TABLE "${table.name}" (\n`;
      
      const columnLines: string[] = [];
      const primaryKeys: string[] = [];

      for (const col of table.columns) {
        let line = `  "${col.name}" ${TypeMapper.map(col.dataType, 'postgres')}`;
        
        if (col.notNull || col.primaryKey) {
          line += ` NOT NULL`;
        }
        
        if (col.unique && !col.primaryKey) {
          line += ` UNIQUE`;
        }
        
        if (col.defaultValue) {
          line += ` DEFAULT ${this.formatDefault(col.defaultValue, col.dataType)}`;
        }
        
        if (col.primaryKey) {
          primaryKeys.push(col.name);
        }
        
        columnLines.push(line);
      }
      
      if (primaryKeys.length > 0) {
        columnLines.push(`  PRIMARY KEY ("${primaryKeys.join('", "')}")`);
      }

      output += columnLines.join(',\n');
      output += `\n);\n\n`;
    }

    // 2. Generate Foreign Keys (ALTER TABLE)
    if (ast.refs.length > 0) {
      output += `-- Foreign Keys\n`;
      for (const ref of ast.refs) {
        const constraintName = `fk_${ref.fromTable}_${ref.fromColumn}`;
        output += `ALTER TABLE "${ref.fromTable}" ADD CONSTRAINT "${constraintName}" FOREIGN KEY ("${ref.fromColumn}") REFERENCES "${ref.toTable}"("${ref.toColumn}");\n`;
      }
    }

    return output;
  }

  private formatDefault(defaultValue: string, dataType: string): string {
    if (defaultValue.toLowerCase() === 'now()') return 'CURRENT_TIMESTAMP';
    
    // If it's a string type and the default isn't already quoted, quote it
    const isString = dataType.toLowerCase().includes('varchar') || dataType.toLowerCase() === 'string' || dataType.toLowerCase() === 'text';
    
    if (isString && !defaultValue.startsWith("'") && !defaultValue.startsWith('"')) {
      return `'${defaultValue}'`;
    }
    
    return defaultValue;
  }
}
