// @ts-nocheck
import type { DslAst, DslTable, DslRef } from '@/features/editor/types/DslAst';
import type { SchemaGenerator } from './SchemaGenerator';
import { TypeMapper } from './TypeMapper';

export class PrismaGenerator implements SchemaGenerator {
  generate(ast: DslAst): string {
    let output = `// Prisma schema generated by SchemaFlow\n`;
    output += `generator client {\n  provider = "prisma-client-js"\n}\n\n`;
    output += `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;

    // A map to store fields injected by reverse-relations (1:N or 1:1)
    const reverseRelations: Record<string, string[]> = {};

    // Pre-calculate reverse relations
    for (const ref of ast.refs) {
      // fromTable -> toTable means toTable has a reverse field pointing to fromTable
      // Typically, the 'fromTable' holds the Foreign Key, pointing to 'toTable'.
      // Wait, in DSL: 'Order.userId > User.id' means Order holds 'userId' pointing to User.
      // So User needs a reverse relation field pointing to Order[].
      
      const isOneToOne = ref.type === '-';
      
      const fromModel = this.formatModelName(ref.fromTable);
      
      const reverseFieldType = isOneToOne ? fromModel : `${fromModel}[]`;
      // Lowercase first letter for field name
      const reverseFieldName = fromModel.charAt(0).toLowerCase() + fromModel.slice(1) + (isOneToOne ? '' : 's');

      if (!reverseRelations[ref.toTable]) reverseRelations[ref.toTable] = [];
      
      // If there are multiple relations between the same tables, we might need relation names, 
      // but for V1 we'll just add the basic reverse field.
      reverseRelations[ref.toTable]?.push(`  ${reverseFieldName} ${reverseFieldType}`);
    }

    // Generate models
    for (const table of ast.tables) {
      output += `model ${this.formatModelName(table.name)} {\n`;
      
      for (const col of table.columns) {
        const type = TypeMapper.map(col.dataType, 'prisma');
        const isOptional = !col.notNull && !col.primaryKey ? '?' : '';
        
        let attributes = [];
        if (col.primaryKey) attributes.push('@id');
        if (col.unique) attributes.push('@unique');
        if (col.defaultValue) {
          if (col.defaultValue.toLowerCase() === 'now()') {
            attributes.push('@default(now())');
          } else if (type === 'String') {
            attributes.push(`@default("${col.defaultValue}")`);
          } else {
            attributes.push(`@default(${col.defaultValue})`);
          }
        }
        
        // Find if this column is a foreign key
        const fKeyRef = ast.refs.find(r => r.fromTable === table.name && r.fromColumn === col.name);
        
        const attrStr = attributes.length > 0 ? ` ${attributes.join(' ')}` : '';
        output += `  ${col.name} ${type}${isOptional}${attrStr}\n`;
        
        // If it's a foreign key, Prisma requires the actual relation object field
        if (fKeyRef) {
          const relationModel = this.formatModelName(fKeyRef.toTable);
          const relationField = relationModel.charAt(0).toLowerCase() + relationModel.slice(1);
          output += `  ${relationField} ${relationModel} @relation(fields: [${col.name}], references: [${fKeyRef.toColumn}])\n`;
        }
      }

      // Inject reverse relations
      if (reverseRelations[table.name]?.length) {
        output += `\n` + reverseRelations[table.name]?.join('\n') + `\n`;
      }

      output += `}\n\n`;
    }

    return output;
  }

  private formatModelName(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1);
  }
}
