import {
  PanelLeft,
  Table2,
  Columns3,
  Trash2,
  Search,
  ZoomIn,
  ZoomOut,
  Plus,
  Pencil,
  Link,
  StickyNote,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronLeft,
  X,
  Check,
  Settings,
  LogOut,
  User,
  FolderOpen,
  FileText,
  Eye,
  EyeOff,
  Copy,
  Clipboard,
  Download,
  Upload,
  MoreHorizontal,
  MoreVertical,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  RefreshCw,
  Loader2,
  Moon,
  Sun,
  Monitor,
  Maximize2,
  Minimize2,
  Grid,
  Move,
  Lock,
  Unlock,
  Key,
  ArrowLeft,
  ArrowRight,
  Layers,
  Share2,
  GitBranch,
  Wand2,
  type LucideProps,
} from 'lucide-react';

export type IconProps = LucideProps;

export {
  Table2 as TableIcon,
  Columns3 as ColumnIcon,
  Trash2 as DeleteIcon,
  Search as SearchIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Plus as AddIcon,
  Pencil as EditIcon,
  Link as RelationshipIcon,
  StickyNote as NoteIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  X as CloseIcon,
  Check as CheckIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  User as UserIcon,
  FolderOpen as ProjectIcon,
  FileText as DiagramIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Copy as CopyIcon,
  Clipboard as PasteIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  AlertTriangle as WarningIcon,
  Info as InfoIcon,
  CheckCircle as SuccessIcon,
  XCircle as ErrorIcon,
  RefreshCw as RefreshIcon,
  Loader2 as SpinnerIcon,
  Moon as MoonIcon,
  Sun as SunIcon,
  Monitor as SystemIcon,
  Maximize2 as MaximizeIcon,
  Minimize2 as MinimizeIcon,
  Grid as GridIcon,
  Move as MoveIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Layers as LayersIcon,
  Share2 as ShareIcon,
  GitBranch as BranchIcon,
  PanelLeft as SidebarIcon,
  Wand2 as AutoLayoutIcon,
};
