export const LIMITS = {
  MAX_TABLE_WIDTH: 400,
  MIN_TABLE_WIDTH: 180,
  DEFAULT_TABLE_WIDTH: 240,
  MAX_NOTE_LENGTH: 2000,
  MAX_COLUMN_NAME_LENGTH: 64,
  MAX_TABLE_NAME_LENGTH: 64,
  MAX_PROJECT_NAME_LENGTH: 100,
  MAX_TABLES_PER_DIAGRAM: 200,
  MAX_COLUMNS_PER_TABLE: 50,
} as const;
