export const CanvasEventType = {
  CANVAS_CLICK: 'CANVAS_CLICK',
  CANVAS_DOUBLE_CLICK: 'CANVAS_DOUBLE_CLICK',
  CANVAS_CONTEXT_MENU: 'CANVAS_CONTEXT_MENU',
  CANVAS_PAN_START: 'CANVAS_PAN_START',
  CANVAS_PAN: 'CANVAS_PAN',
  CANVAS_PAN_END: 'CANVAS_PAN_END',
  CANVAS_ZOOM: 'CANVAS_ZOOM',

  TABLE_CREATED: 'TABLE_CREATED',
  TABLE_SELECTED: 'TABLE_SELECTED',
  TABLE_MOVED: 'TABLE_MOVED',
  TABLE_RESIZED: 'TABLE_RESIZED',
  TABLE_RENAMED: 'TABLE_RENAMED',
  TABLE_COLOR_CHANGED: 'TABLE_COLOR_CHANGED',
  TABLE_DELETED: 'TABLE_DELETED',

  COLUMN_CREATED: 'COLUMN_CREATED',
  COLUMN_UPDATED: 'COLUMN_UPDATED',
  COLUMN_MOVED: 'COLUMN_MOVED',
  COLUMN_DELETED: 'COLUMN_DELETED',
  COLUMN_NOTE_UPDATED: 'COLUMN_NOTE_UPDATED',

  RELATIONSHIP_CREATED: 'RELATIONSHIP_CREATED',
  RELATIONSHIP_UPDATED: 'RELATIONSHIP_UPDATED',
  RELATIONSHIP_DELETED: 'RELATIONSHIP_DELETED',
  RELATIONSHIP_SELECTED: 'RELATIONSHIP_SELECTED',

  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_UPDATED: 'NOTE_UPDATED',
  NOTE_RESIZED: 'NOTE_RESIZED',
  NOTE_MOVED: 'NOTE_MOVED',
  NOTE_DELETED: 'NOTE_DELETED',

  VIEWPORT_CHANGED: 'VIEWPORT_CHANGED',
  ZOOM_CHANGED: 'ZOOM_CHANGED',
  PAN_CHANGED: 'PAN_CHANGED',
  FIT_CONTENT: 'FIT_CONTENT',
  CENTER_VIEW: 'CENTER_VIEW',

  DELETE: 'DELETE',
  ESCAPE: 'ESCAPE',
  COPY: 'COPY',
  PASTE: 'PASTE',
  UNDO: 'UNDO',
  REDO: 'REDO',
  SELECT_ALL: 'SELECT_ALL',
  DUPLICATE: 'DUPLICATE',
} as const;

export type CanvasEventTypeValue = (typeof CanvasEventType)[keyof typeof CanvasEventType];

export interface CanvasEvent<T = unknown> {
  id: string;
  type: CanvasEventTypeValue;
  timestamp: number;
  payload: T;
}
